# Generated by Django 2.2.7 on 2019-11-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='workplace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker_managment.Workplace'),
        ),
    ]
