# Generated by Django 2.2.7 on 2019-11-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_managment', '0002_auto_20191127_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='workplace',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker_managment.Workplace'),
        ),
    ]
