# Generated by Django 3.0 on 2019-12-02 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_managment', '0002_auto_20191130_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker_managment.Workplace'),
        ),
    ]
