# Generated by Django 2.2.7 on 2019-12-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_managment', '0003_auto_20191202_1711'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worktime',
            unique_together={('worker', 'workplace')},
        ),
    ]
