# Generated by Django 2.2.7 on 2019-12-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_managment', '0004_auto_20191204_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Cancelled'), (3, 'Finished')], default=0),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Cancelled')], default=0),
        ),
    ]
