# Generated by Django 3.0 on 2020-01-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_managment', '0005_auto_20191206_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='date_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='date_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Cancelled')], default=0, verbose_name='status'),
        ),
    ]
